version: '4'
services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - '27017:2701'
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data:/data/db