version: '4'
services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql-order
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - '3307:3306'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql